package com.connectsoar.backend.enums;

public enum AuditAction {
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_DISABLED,
    EMPLOYEE_ENABLED,
    ROLE_CHANGED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    MEETING_CREATED,
    MEETING_UPDATED,
    MEETING_CANCELLED,
    PARTICIPANT_ADDED,
    PARTICIPANT_REMOVED,
    PARTICIPANT_UPDATED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED
}
