package com.connectsoar.backend.enums;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    FORBIDDEN,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    PASSWORD_CHANGE_REQUIRED,
    USER_INACTIVE,
    USER_SUSPENDED,
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    VALIDATION_ERROR,
    RATE_LIMITED,
    RESOURCE_NOT_FOUND,
    ACCESS_DENIED,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR
}
